# Server configurations
isu:
  host: "localhost"
  port: 3000
frecuencia: 60
# Database credentials
batchs:
  - batch: 1000
  - batch: 1001
  - batch: 1002
  - batch: 1003
  - batch: 1004
  - batch: 1005
lista: 1000, 1001, 1002, 1003, 1004, 1005